# ATTENTION: Update the following files before compiling:
#      packages/jb_base.pkg/common/secrets.yaml
#      packages/jb_base.pkg/common/wifi.inc.yaml
substitutions:
  # This will be the host name
  node_name: your_node_name
  friendly_node_name: Led Driver 1
  log_level: INFO


packages:
  board: !include packages/jb_base.pkg/esp8266_d1_mini.yaml
  default_sensors: !include packages/jb_base.pkg/default_sensors.yaml
  default_controls: !include packages/jb_base.pkg/default_controls.yaml

sensor:
  - platform: bme280
    address: 0x76
    temperature:
      name: "${friendly_node_name} Temperature"
      id: "${node_name}_temperature_bme"
      oversampling: 2x
    pressure:
      name: "${friendly_node_name} Pressure"
      id: "${node_name}_pressure"
      oversampling: 2x
    humidity:
      name: "${friendly_node_name} Humidity"
      id: "${node_name}_humidity"
      oversampling: 2x
    update_interval: "${bme280_update_interval}"
  - platform: mhz19
    co2:
      name: "${friendly_node_name} CO2"
      id: "${node_name}_co2"
    update_interval: "${co2_update_interval}"
    automatic_baseline_calibration: false
