esphome:
  name: prototype_heater_thermostat
  platform: ESP8266
  board: d1_mini
  build_path: build/prototype_heater_thermostat

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .home

# Enable logging
logger:
  logs:
    sensor: INFO
    adc: INFO

api:
  reboot_timeout: 0s

ota:
  safe_mode: true
  password: !secret ota_password

time:
  - platform: sntp
    id: homeassistant_time
    servers: 192.168.88.1
    timezone: Europe/Kiev
#
#light:
#  - platform: monochromatic
#    id: led_garland
#    name: "Garland Lights"
#    output: led_pwm_garland
#    default_transition_length: 0.2s
#    effects:
#      - pulse:
#          transition_length: 5s
#          update_interval: 5s
#
#  - platform: monochromatic
#    id: led_spot
#    name: "Spot Reading Light"
#    output: led_pwm_spot
#
#output:
#  - platform: esp8266_pwm
#    id: led_pwm_spot
#    pin: D1
#  - platform: esp8266_pwm
#    id: led_pwm_garland
#    pin: D8

switch:
  platform: gpio
  name: "Relay for Heater"
  pin: D5
#binary_sensor:
#  - platform: gpio
#    name: "Rotary Button"
#    pin: D5
#    on_press:
#      - logger.log: "Rotary button pressed"
#  - platform: gpio
#    name: "Switch Decorations"
#    pin: D7
#    on_press:
#      - logger.log: "Switch Decoration Toggle"
#
#  - platform: gpio
#    name: "Switch Noise"
#    pin: D4
#    on_press:
#      - logger.log: "Switch Decoration Toggle"
#
#  - platform: gpio
#    name: "Switch Night Light"
#    pin: D2
#    on_press:
#      - logger.log: "Switch Decoration Toggle"
#
#
#sensor:
#  - platform: rotary_encoder
#    name: "Rotary Encoder"
#    pin_a: D6
#    pin_b: D5
#    min_value: 0
#    max_value: 100
#    #    on_clockwise:
#    #      - logger.log: "Turned Clockwise"
#    #    on_anticlockwise:
#    #      - logger.log: "Turned Anticlockwise"
#    on_anticlockwise:
#      then:
#        - light.dim_relative:
#            id: led_spot
#            relative_brightness: -4%
#    on_clockwise:
#      then:
#        - light.dim_relative:
#            id: led_spot
#            relative_brightness: 4%
