esphome:
  name: prototype_christmas_tree
  platform: ESP8266
  board: d1_mini
  build_path: build/prototype_christmas_tree

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .home

# Enable logging
logger:
  logs:
    sensor: INFO
    adc: INFO

api:
  reboot_timeout: 0s

ota:
  safe_mode: true
  password: !secret ota_password

time:
  - platform: sntp
    id: homeassistant_time
    servers: 192.168.88.1
    timezone: Europe/Kiev

light:
  - platform: monochromatic
    id: led_a
    name: "Garland A"
    output: led_pwm_a
    restore_mode: RESTORE_DEFAULT_ON
    effects:
      - pulse:
          name: default_pulse_a
          transition_length: 3s
          update_interval: 3s
    on_turn_on:
      then:
        - light.control:
            id: led_a
            effect: default_pulse_a

  - platform: monochromatic
    id: led_b
    name: "Garland B"
    output: led_pwm_b
    restore_mode: RESTORE_DEFAULT_ON
    effects:
      - pulse:
          name: default_pulse_b
          transition_length: 30s
          update_interval: 30s
    on_turn_on:
      then:
        - light.control:
            id: led_b
            effect: default_pulse_b


output:
  - platform: esp8266_pwm
    id: led_pwm_a
    pin: D5
  - platform: esp8266_pwm
    id: led_pwm_b
    frequency: 160Hz
    pin: D6

binary_sensor:
  - platform: gpio
    pin:
      number: D7
      mode: INPUT_PULLUP
    name: "Control Button"
    on_press:
      - light.toggle: led_a
      - light.toggle: led_b