esphome:
  name: ${node_name}
  platform: ESP8266
  board: esp01_1m
  build_path: ./build/${node_name}

# Enable logging
logger:
  baud_rate: 0
  level: ${log_level}

# NTP Configuration
time:
  - <<: !include ./common/time.config.yaml

# Wi-Fi Configuration
<<: !include ./common/wifi.inc.yaml

# Enable Over the Air updates
<<: !include ./common/ota.inc.yaml

# Enable Home Assistant API
<<: !include common/api.inc.yaml

status_led:
  pin:
    number: GPIO13
    inverted: yes

remote_receiver:
  pin:
    number: 4
#    inverted: yes
#    mode: INPUT_PULLUP
  dump:
    - rc_switch
    - rc5
#  filter: 50us
#  idle: 10ms
#  tolerance: 50

remote_transmitter:
  pin: 5
  carrier_duty_percent: 50%